export const LOGIN_SERVICE = "/Users/Login";
export const REGISTER_SERVICE = "/Users/Register";
export const GET_PROFILE_SERVICE = "/Users/GetProfile";
export const INSERT_PROJECT_SERVICE = "/Projects/Insert";
export const GET_PROJECTS_SERVICE = "/Projects/GetMyProjects";
export const GET_TASKS_SERVICE = "/Tasks/GetTasks";
export const GET_TASK_DETAIL = "/Tasks/GetById/";
export const GET_PROJECT_PARTICIPANTS_SERVICE =
  "/Projects/GetProjectParticipants";
export const INSERT_TASK_SERVICE = "/Tasks/Insert";
export const UPDATE_TASK_SERVICE = "/Tasks/Update";
export const UPDATE_TASK_STATUS_SERVICE = '/Tasks/UpdateTaskStatus'
export const GET_PROJECT_DETAIL = "/Projects/GetById/";
export const GET_TASK_WORK_LOGS = "/WorkLogs/GetWorkLogs"
export const GET_PROJECT_WORK_LOGS = "/WorkLogs/GetProjectWorkLogs"
export const INSERT_WORK_LOG_SERVICE = '/WorkLogs/Insert'
export const GET_SUBTASKS_SERVICE = '/Tasks/GetSubTasks'
export const GET_PARTICIPANT_ROLE = '/Projects/GetRole/'
export const GET_PROJECT_REPORT = '/Reports/GetProjectReport/'
export const GET_TASK_TIMELINE = '/Tasks/GetTaskTimeline/'
export const UPLOAD_PROJECT_FILE = '/Projects/UploadFile/'
export const UPLOAD_TASK_FILE = '/Tasks/UploadFile/'
export const INVITE_PARTICIPANT = '/Projects/InviteParticipant/'
export const REMOVE_PARTICIPANT = '/Projects/RemoveParticipant/'
export const GET_MY_TASKS = '/Tasks/GetMyTasks'
export const GET_ACTIVITY_STREAM = '/WorkLogs/GetActivityStream'