export const SCREEN_ENUMS = {
  APP: 'SCREEN_APP',
  SIGN_IN: 'SCREEN_SIGN_IN',
  SIGN_UP: 'SCREEN_SIGN_UP',
  HOME: 'SCREEN_HOME',
  GET_STARTED: 'SCREEN_GET_STARTED',
  PROFILE: 'SCREEN_PROFILE',
  TASK: 'SCREEN_TASK',
  PROJECT: 'PROJECT',
  NOTIFICATIONS: 'NOTIFICATIONS'
};
